### ISSUE TITLE
Tacker parser

### ISSUE THREAD

**Issue by bhberson** [RIAEvangelist/node-dominos-pizza-api#43]
/Users/bberson/invoca/pizzadash/node_modules/dominos/src/Track.js:53
            result = parser.toJson(
                     ^
ReferenceError: parser is not defined
    at Request._callback (/Users/bberson/invoca/pizzadash/node_modules/dominos/src/Track.js:53:22)
    at Request.self.callback (/Users/bberson/invoca/pizzadash/node_modules/dominos/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/bberson/invoca/pizzadash/node_modules/dominos/node_modules/request/request.js:1063:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/bberson/invoca/pizzadash/node_modules/dominos/node_modules/request/request.js:1009:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by RIAEvangelist** [comment]
@julianh2o  sorry meant to assign to me, my bad

**Comment by zifu** [comment]
Need to add
```var parser = require('xml2json');```
to Track.js
